Shell integration updates..

diff --git a/vmw-cli b/vmw-cli
--- a/vmw-cli
+++ b/vmw-cli
@@ -4,25 +4,84 @@ if [[ $0 =~ ^(.*)/([^/]+)$ ]]; then
 	CALLED="${BASH_REMATCH[2]}"
 fi
 
-# launch & persist (run + exec)
-#if [[ -n "$1" ]]; then
-	case "${1}" in
-		'stop') ## list commands
-			printf "[apnex/${CALLED}] stopping\n" 1>&2
-			docker rm -f ${CALLED} 2>/dev/null
-		;;
-		*) ## cleanup stopped - then launch + persist (run + exec)
-			docker rm -v $(docker ps -qa -f name=${CALLED} -f status=exited) 2>/dev/null
-			RUNNING=$(docker ps -q -f name="${CALLED}")
-			if [[ -z "$RUNNING" ]]; then
-				printf "[apnex/${CALLED}] not running - now starting\n" 1>&2
-				docker run -id --name ${CALLED} -e VMWUSER -e VMWPASS -v ${PWD}:/files --entrypoint=/bin/sh apnex/${CALLED} 1>&2
+## cli name
+CNAME="vmw-cli"
+
+## list local shell env variables to be passed to container here
+LENV=()
+LENV+=("VMWUSER")
+LENV+=("VMWPASS")
+
+## return specific running container env value
+CENV=()
+cget() {
+	for ITEM in ${CENV[@]}; do
+		if [[ ${ITEM} =~ ([0-9a-zA-Z]+)=(.*)\" ]]; then
+			if [[ "${BASH_REMATCH[1]}" == "${1}" ]]; then
+				printf "${BASH_REMATCH[2]}"
 			fi
-			### check if VMWUSER and VMWPASS match running container, if not, restart
-			RUNNING=$(docker ps -q -f name="${CALLED}")
-			if [[ -n "$RUNNING" ]]; then
-				docker exec -t ${CALLED} ${CALLED} "${@}"
+		fi
+	done
+}
+
+## compare defined local values against running container
+lget() {
+	local PASS=1
+	for ITEM in ${LENV[@]}; do
+		local LVAL=${!ITEM}
+		local CVAL=$(cget ${ITEM})
+		if [[ -n ${LVAL} && ${LVAL} != ${CVAL} ]]; then
+			PASS=0
+		fi
+	done
+	printf ${PASS}
+}
+
+## force stop and clear any dangling containers
+cstop() {
+	docker rm -f ${CNAME} 2>/dev/null
+	docker rm -v $(docker ps -qa -f name=${CNAME} -f status=exited) 2>/dev/null
+}
+
+## start new instance of container with fresh env vars
+cstart() {
+	## build env string
+	local DSTRING
+	for ITEM in ${LENV[@]}; do
+		local LVAL=${!ITEM}
+		if [[ -n ${LVAL} ]]; then
+			DSTRING+=" -e ${ITEM}"
+		fi
+	done
+	DSTRING+=" -v ${PWD}:/files"
+	docker rm -v $(docker ps -qa -f name=${CNAME} -f status=exited) 2>/dev/null
+	docker run -id --name ${CNAME} ${DSTRING} --entrypoint=/bin/sh apnex/${CNAME} 1>&2
+}
+
+## exec normal commands
+cexec() {
+	docker exec -t ${CNAME} ${CNAME} "${@}"
+}
+
+# main
+case "${1}" in
+	'stop') ## force stop
+		printf "[apnex/${CNAME}] stopping\n" 1>&2
+		cstop
+	;;
+	*) # launch + persist (run + exec)
+		RUNNING=$(docker ps -q -f name="${CNAME}")
+		if [[ -n "$RUNNING" ]]; then
+			CENV=$(docker inspect -f "{{json .Config.Env }}" ${CNAME} | tr "," "\n")
+			if [[ $(lget) == 0 ]]; then
+				# env match failed, restart container with new env
+				cstop
+				cstart
 			fi
-		;;
-	esac
-#fi
+			cexec "${@}"
+		else
+			printf "[apnex/${CALLED}] not running - now starting\n" 1>&2
+			cstart
+		fi
+	;;
+esac
